### ISSUE TITLE
Acesso aos serviços prestados pelo governo de Alagoas

### ISSUE THREAD

**Issue by eucandre** [juliohm/awesome-brazil-data#4]
Olá, o estado de Alagoas conta com uma API que retorna todos os serviços do governo do estado.
Acesse o endereço servicos.al.gov.br/api, lá poderá encontrar uma documentação sobre a ferramenta.
Esse recurso já está ligado ao governo federal.

**Comment by juliohm** [comment]
Boa noite Andre, esses servicos seriam dados? Este repositorio se refere a fontes de dados dos estados. A API parece retornar servicos oferecidos pelo estado.
